using HotPreview.SharedModel;
using HotPreview.SharedModel.Protocol;

namespace HotPreview.Tooling;

public class GetPreviewsFromProtocol : PreviewsManagerBuilderTooling
{
    /// <summary>
    /// Initializes a new instance of GetPreviewsFromProtocol and processes the UI component information from the app,
    /// creating and organizing UI components based on the provided data.
    /// </summary>
    /// <param name="uiComponentInfos">Array of UI component information from the protocol</param>
    /// <param name="previewCommandInfos">Array of preview command information from the protocol</param>
    public GetPreviewsFromProtocol(UIComponentInfo[] uiComponentInfos, PreviewCommandInfo[] previewCommandInfos)
    {
        foreach (UIComponentInfo uiComponentInfo in uiComponentInfos)
        {
            // Create the UI component and add it to the builder
            UIComponentKind componentKind = UIComponentKindInfo.ToUIComponentKind(uiComponentInfo.UIComponentKindInfo);
            var uiComponent = new UIComponentTooling(componentKind, uiComponentInfo.Name, uiComponentInfo.DisplayName,
                uiComponentInfo.Previews.Select(CreatePreview).ToList());

            // Add the component to the builder
            AddOrUpdateUIComponent(uiComponent);
        }

        foreach (PreviewCommandInfo previewCommandInfo in previewCommandInfos)
        {
            // Create the preview command and add it to the builder
            var command = new PreviewCommandTooling(previewCommandInfo.Name, previewCommandInfo.DisplayName);
            AddOrUpdateCommand(command);
        }
    }

    /// <summary>
    /// Creates a PreviewTooling object from protocol PreviewInfo.
    /// </summary>
    /// <param name="previewInfo">Preview information from the protocol</param>
    /// <returns>A PreviewTooling object</returns>
    private static PreviewTooling CreatePreview(PreviewInfo previewInfo)
    {
        return previewInfo.PreviewType switch
        {
            PreviewTypeInfo.Class => new PreviewClassTooling(previewInfo.Name, previewInfo.DisplayName, previewInfo.AutoGenerated),
            PreviewTypeInfo.StaticMethod => new PreviewStaticMethodTooling(previewInfo.Name, previewInfo.DisplayName),
            _ => throw new NotImplementedException($"Unknown preview type: {previewInfo.PreviewType}")
        };
    }
}
