namespace PreviewFramework.Tooling;

public class PreviewClassTooling(string classFullName, string? displayNameOverride, bool isAutoGenerated) : PreviewTooling(classFullName, displayNameOverride)
{
    public override bool IsAutoGenerated => isAutoGenerated;
}
