using System;

namespace Microsoft.PreviewFramework.App;

public class UIPreviewClassReflection : UIPreviewReflection
{
    bool isAutoGenerated = false;

    public UIPreviewClassReflection(PreviewAttribute previewAttribute, Type type) : base(previewAttribute)
    {
        Type = type;
    }

    public UIPreviewClassReflection(Type type, bool isAutoGenerated) : base(type)
    {
        Type = type;
        this.isAutoGenerated = isAutoGenerated;
    }

    public Type Type { get; }

    public override object Create()
    {
        return Activator.CreateInstance(Type);
    }

    public override Type? DefaultUIComponentType => null;

    public override string Name => Type.FullName;

    public override bool IsAutoGenerated => isAutoGenerated;
}
