using System;

namespace Microsoft.UIPreview.App;

public class PreviewClassReflection : PreviewReflection
{
    bool isAutoGenerated = false;

    public PreviewClassReflection(PreviewAttribute previewAttribute, Type type) : base(previewAttribute)
    {
        Type = type;
    }

    public PreviewClassReflection(Type type, bool isAutoGenerated) : base(type)
    {
        Type = type;
        this.isAutoGenerated = isAutoGenerated;
    }

    public Type Type { get; }

    public override object Create()
    {
        return Activator.CreateInstance(Type);
    }

    public override Type? DefaultUIComponentType => null;

    public override string Name => Type.FullName;

    public override bool IsAutoGenerated => isAutoGenerated;
}
