namespace PreviewFramework.Tooling;

public class PreviewClass(string classFullName, string? displayNameOverride, bool isAutoGenerated) : Preview(classFullName, displayNameOverride)
{
    public override bool IsAutoGenerated => isAutoGenerated;
}
