namespace PreviewFramework.Tooling;

public class PreviewClass : Preview
{
    readonly bool _isAutoGenerated = false;

    public PreviewClass(string classFullName, string? displayNameOverride) : base(classFullName, displayNameOverride)
    {
    }

    public PreviewClass(string classFullName, bool isAutoGenerated) : base(classFullName, null)
    {
        this._isAutoGenerated = isAutoGenerated;
    }

    public override bool IsAutoGenerated => _isAutoGenerated;
}
