using System.Text.Json.Serialization;

namespace HotPreview.SharedModel.Protocol;

public record PreviewInfo(
    [property: JsonPropertyName("previewType")] string PreviewType,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("displayName")] string? DisplayName,
    [property: JsonPropertyName("autoGenerated")] bool AutoGenerated
);
