using System.Text.Json.Serialization;

namespace HotPreview.SharedModel.Protocol;

public class PreviewInfo(string previewType, string name, string? displayName, bool autoGenerated)
{
    [JsonPropertyName("previewType")] public string PreviewType { get; } = previewType;
    [JsonPropertyName("name")] public string Name { get; } = name;
    [JsonPropertyName("displayName")] public string? DisplayName { get; } = displayName;
    [JsonPropertyName("autoGenerated")] public bool AutoGenerated { get; } = autoGenerated;
}
