using Microsoft.Build.Framework;
using System.IO;

namespace PreviewFramework.AppBuildTasks
{
    public class GeneratePreviewAppSettingsTask : Microsoft.Build.Utilities.Task
    {
        [Required]
        public required string ProjectPath { get; set; }

        [Required]
        public required string ToolingConnection { get; set; }

        [Required]
        public required string OutputPath { get; set; }

        public override bool Execute()
        {
            try
            {
                string projectPath = Path.GetFullPath(ProjectPath);
                string toolingConnection = ToolingConnection;
                string outputPath = Path.GetFullPath(OutputPath);
                string? outputDirectory = Path.GetDirectoryName(outputPath);

                if (outputDirectory is not null && !Directory.Exists(outputDirectory))
                {
                    Directory.CreateDirectory(outputDirectory);
                }

                // Escape backslashes and quotes for the C# string literal
                string escapedProjectPath = projectPath.Replace("\\", "\\\\").Replace("\"", "\\\"");
                string escapedToolingConnection = toolingConnection.Replace("\\", "\\\\").Replace("\"", "\\\"");

                string content = @"// <auto-generated/>
namespace PreviewFramework.App
{
    public static partial class GeneratedPreviewAppSettings
    {
        public static string ProjectPath { get; } = @"""" + escapedProjectPath + @"""";
        public static string ToolingConnection { get; } = @"""" + escapedToolingConnection + @"""";
    }
}";

                File.WriteAllText(outputPath, content);
                return true;
            }
            catch (System.Exception ex)
            {
                Log.LogErrorFromException(ex);
                return false;
            }
        }
    }
}
