namespace Microsoft.PreviewFramework.Tooling;

public class UIPreviewClass : UIPreview
{
    bool isAutoGenerated = false;

    public UIPreviewClass(string classFullName, string? displayName) : base(classFullName, displayName)
    {
    }

    public UIPreviewClass(string classFullName, bool isAutoGenerated) : base(classFullName, null)
    {
        this.isAutoGenerated = isAutoGenerated;
    }

    public override bool IsAutoGenerated => this.isAutoGenerated;
}
